
stages:          # List of stages for jobs, and their order of execution
  - generate
  - install-validator
  - validate
  - upload

image: ubuntu


.build:
 stage: generate
 image: ubuntu
 script:
  - apt update --yes
  - apt install libicu-dev --yes
  - pushd .
  - cd linux
  - chmod +x GenerateAll.sh
  - ./GenerateAll.sh
  - popd
  - mkdir -p mixed
  - cp hand-written/* generated/* mixed 
 artifacts:
  untracked: false
  when: on_success
  access: all
  expire_in: "30 days"
  paths:
  - generated
  - hand-written
  - mixed
  
.get-files:
  image: ubuntu
  stage: install-validator
  script:
    - apt-get update --yes
    - apt-get install wget --yes
    - wget https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
  artifacts:
    paths:
      - validator_cli.jar

.run-validator:
  stage: validate
  script:
    - apt-get update --yes
    - apt-get install default-jdk --yes
#    - java -jar validator_cli.jar hand-written/*.json -version 4.0.1 -tx https://tx.dev.hl7.org.au/fhir -ig hl7.fhir.au.core#0.4.0-preview -sct au -level errors -jurisdiction au -html-output h_validation.html -output h_validation.xml
#    - java -jar validator_cli.jar generated/*.json -version 4.0.1 -tx https://tx.dev.hl7.org.au/fhir -ig hl7.fhir.au.core#0.4.0-preview -sct au -level errors -jurisdiction au -html-output g_validation.html -output g_validation.xml   
    - java -jar validator_cli.jar mixed/*.json -version 4.0.1 -tx https://tx.dev.hl7.org.au/fhir -ig hl7.fhir.au.core#0.4.0-preview  -sct au -level errors -jurisdiction au -html-output m_validation.html -output m_validation.xml
    - apt-get install xsltproc --yes
    - xsltproc extract_error_files.xsl m_validation.xml > quarantine_errors.sh
    - chmod +x quarantine_errors.sh 
    - ./quarantine_errors.sh
    - java -jar validator_cli.jar mixed/*.json -version 4.0.1 -tx https://tx.dev.hl7.org.au/fhir -ig hl7.fhir.au.core#0.4.0-preview  -sct au -level errors -jurisdiction au -html-output m_validation.html -output m_validation.xml
  artifacts:  
    paths:
      - "*_validation.xml"
      - "*_validation.html"
      - quarantined
      - mixed
    
upload-resources:
  stage: upload
#  services:
#    - name: hapiproject/hapi:latest
#      alias: hapi
  image: ubuntu:latest
  variables:
     UPLOAD_SOURCE : ${CI_PROJECT_DIR}/mixed
     TARGET_FHIR_SERVER: https://fhir.hl7.org.au/aucore/fhir/csirotest/
# "http://hapi:8080""  
  script:
# cannot add, am not root
#     - apk update
#     - apk upgrade
#     - apk install ncurses
     - export PATH=/home/smile/smilecdr/bin:$PATH
     - echo ${UPLOAD_SOURCE}
# https://smilecdr.com/docs/smileutil/synchronize_fhir_servers.html#using-a-directory-as-the-source
# Extracting resources in use 
# cd mixed
# https://stackoverflow.com/questions/1251999/how-can-i-replace-each-newline-n-with-a-space-using-sed#answer-1252191
# jq --slurp '.[].resourceType' *.json | sort | uniq > summary.txt
# cat summary.txt | sed -e 's/"//g' | sed ':a;N;$!ba;s/\n/,/g' > resources_in_use.txt 
#     - smileutil synchronize-fhir-servers --source "file://${UPLOAD_SOURCE}" --target "${TARGET_FHIR_SERVER}" --fhir-version R4 --mode COMPARE --target-basic-auth ${FHIR_USER_ID}:${FHIR_USER_PASSWORD} --resource-types "AllergyIntolerance, Condition, Encounter, Immunization, Location, Medication, MedicationRequest, Observation, Organization, Patient, Practitioner, PractitionerRole, Procedure"
     - apt update --yes
# see if this fixes certificate chains
     - apt upgrade --yes     
     - apt install libicu-dev --yes
     - export CREDENTIALS=`echo ${FHIR_USER_ID}:${FHIR_USER_PASSWORD} | base64`
     - cd linux
     - chmod +x UploadAll.sh
     - ./UploadAll.sh
     - ./compiledUploadScript.sh ${TARGET_FHIR_SERVER} ${CREDENTIALS}