name: Report to action summary
inputs:
  title:
    description: "Report title"
  ig:
    description: "IG to validate against"
  paths:
    description: "Paths to be validate"

runs:
  using: 'composite'
  steps:
    - id: validation-result
      name: Upload HTML validation result
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.title}} validation result"
        path: g_validation.html
    - id: generate-report
      shell: bash
      run: python ./.github/report/process_result.py -r g_validation.json -q ./.github/report/quarantine >> "$GITHUB_OUTPUT"
    - name: Generate list using Markdown
      shell: bash
      run: |
        echo "# ${{ inputs.title}} Validation Report" >> $GITHUB_STEP_SUMMARY
        echo "### Run detail" >> $GITHUB_STEP_SUMMARY
        echo "IG: ${{ inputs.ig }}" >> $GITHUB_STEP_SUMMARY
        echo "Resources: ${{ inputs.paths }}" >> $GITHUB_STEP_SUMMARY
        echo "### Validation Result" >> $GITHUB_STEP_SUMMARY
        echo " âœ… Pass: ${{ steps.generate-report.outputs.pass }} (${{ steps.generate-report.outputs.warning }} with warning âš ï¸)" >> $GITHUB_STEP_SUMMARY
        echo " âŽ Error: ${{ steps.generate-report.outputs.error }} " >> $GITHUB_STEP_SUMMARY
        echo " ðŸš« Quarantined: ${{ steps.generate-report.outputs.quarantine }} " >> $GITHUB_STEP_SUMMARY
        echo "### Note" >> $GITHUB_STEP_SUMMARY
        echo "See **Artifacts** sections below for detailed report. " >> $GITHUB_STEP_SUMMARY
        echo "See \`.github/report/quarantine\` for quarantined resources. " >> $GITHUB_STEP_SUMMARY
    - shell: bash
      name: Fail in case of validation error
      if: steps.generate-report.outputs.error != '0'
      run: exit -1
