name: Validate generated files
inputs:
  path:
    description: "Path to validate"
    default: 'generated'
  ig:
    description: "Implementation guide used to validate"
    default: 'hl7.fhir.au.core#2.0.0-ballot'
  tx:
    description: "Terminology server"
    default: "https://tx.dev.hl7.org.au/fhir"
  title:
    description: ""


runs:
  using: 'composite'
  steps:
    # - name: Don't validate quarantine files
    #   shell: bash
    #   run: |
    #     mkdir ${{ runner.temp }}/quarantine &&\
    #     mv -v `grep -v '^#' ./.github/validate/validator_quarantine | grep ${{ inputs.path }}` ${{ runner.temp }}/quarantine
      # continue-on-error: true
    - shell: bash
      run: wget https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
    - name: Run validator
      shell: bash
      run: |
        java -jar validator_cli.jar ${{ inputs.path }} \
             -version 4.0.1 -tx ${{ inputs.tx }} \
             -ig ${{ inputs.ig }} -sct au \
             -level errors -jurisdiction au \
             -html-output g_validation.html -output g_validation.xml
    - id: validation-result
      name: Archive validation result
      uses: actions/upload-artifact@v4
      with:
        name: "${{ inputs.title}} validation result"
        path: g_validation.html
    # - name: Restore skipped files
    #   shell: bash
    #   run: mv -v ${{ runner.temp }}/quarantine/* ${{ inputs.path }}
    #   continue-on-error: true
