name: Validate generated files
inputs:
  path:
    description: "Directory to validate"
    default: 'generated'
  ig:
    description: "Implementation guide used to validate"
    default: 'hl7.fhir.au.core#1.1.0-preview'
  tx:
    description: "Terminology server"
    default: "https://tx.dev.hl7.org.au/fhir"


runs:
  using: 'composite'
  steps:
    - name: Don't validate quarantine files
      shell: bash
      run: |
        mkdir ${{ runner.temp }}/quarantine &&\
        mv -v `grep -v '^#' ./quarantine | grep ${{ inputs.path }}` ${{ runner.temp }}/quarantine
      continue-on-error: true
    - shell: bash
      run: wget https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar
    - name: Run validator
      shell: bash
      run: |
        java -jar validator_cli.jar ${{ inputs.path }}/*.json \
             -version 4.0.1 -tx ${{ inputs.tx }} \
             -ig ${{ inputs.ig }} -sct au \
             -level errors -jurisdiction au \
             -html-output g_validation.html -output g_validation.xml
    - name: Restore skipped files
      shell: bash
      run: mv -v ${{ runner.temp }}/quarantine/* ${{ inputs.path }}
      continue-on-error: true
