@startdot


digraph Process  {

overlap="false"

edit [label="Edit CSVs"]
generate [label="Generate JSON"]
upload [label="Upload Resources"]
verify [shape="diamond", label="Check data behaves\nas expected"]
start  [shape="point"]
publish  [shape="cds"]


start -> edit -> generate -> upload -> verify -> edit 
verify -> publish
}

@enddot