# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "ci-cd" ]

jobs:
  Build:
    strategy:
      matrix:
        program: [Csv2FhirMapping, TestDataClient]
        os: [win, linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build ${{ matrix.program }} on ${{ matrix.os }}
      run: |
        dotnet publish Sparked.${{ matrix.program }}/Sparked.${{ matrix.program }}.csproj --arch x64 --os ${{ matrix.os }} --configuration Release -p:PublishSingleFile=True --framework net70 --self-contained true --output "Sparked.${{ matrix.program }}-${{ matrix.os }}Output"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.program }}-${{ matrix.os }}-binaries
        path: |
          Sparked.${{ matrix.program }}-${{ matrix.os }}Output
  Generate:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Download Csv2FhirMapping
      uses: actions/download-artifact@v4
      with:
        name: Csv2FhirMapping-linux-binaries
    - run: |
        ls -la
    - name: Generate resources
      # You may pin to the exact commit or the version.
      # uses: daaku/gh-action-apt-install@92eea4f84f90c895b544aaec6ae21839127c84e5
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        # Packages to install.
        packages:
          libicu-dev
        execute_install_scripts: true
    - run: |
         mkdir generated
         pushd .
         cd linux
         chmod +x GenerateAll.sh
         ./GenerateAll.sh
         popd
    - name: Archive generated resources
      uses: actions/upload-artifact@v4
      with:
        name: generated-resources
        path: generated
