# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "27-add-linux-build-files" ]
  pull_request:
    branches: [ "27-add-linux-build-files" ]

jobs:
  product_matrix:
    strategy:
      matrix:
        program: [Csv2FhirMapping, TestDataClient]
        runtime: [win-x64, linux-x64]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
#    - name: Restore dependencies
#      run: dotnet restore Sparked.Csv2FhirMapping/Sparked.Csv2FhirMapping.sln
    - name: Build ${{ matrix.program }} on ${{ matrix.runtime }}
      run: | 
        dotnet publish Sparked.${{ matrix.program }}/Sparked.${{ matrix.program }}.csproj --runtime ${{ matrix.runtime }} --configuration Release -p:PublishSingleFile=True --framework net70 --self-contained true --output "Sparked.${{ matrix.program }}-${{ matrix.runtime }}Output"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          Sparked.${{ matrix.program }}-${{ matrix.runtime }}Output

#    - name: Test
#      run: dotnet test --no-build --verbosity normal
