name: Reference Integrity Check

on:
  pull_request:

jobs:
  run-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run Python script
        run: |
          python .github/scripts/reference_integrity.py

      - name: Prepare result JSON
        run: |
          if [ -f reference_errors.json ]; then
            echo '{"result":"FAIL :red_circle:","errors":'$(cat reference_errors.json)'}' > result.json
          else
            echo '{"result":"PASS :white_check_mark:","errors":{}}' > result.json
          fi

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: reference-check-result
          path: result.json

      - name: Fail if errors found
        run: |
          if [ -f reference_errors.json ]; then
            echo "Reference integrity errors found. Failing the workflow."
            exit 1
          fi
