name: Reference Integrity Check

on:
  pull_request:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Python script
        id: run_script
        run: |
          python .github/scripts/reference_integrity.py

      - name: Check for error file, set result, fail if errors found
        id: set_result
        run: |
          if [ -f reference_errors ]; then
            echo "Reference Integrity Check failed" >> $GITHUB_STEP_SUMMARY
            echo "$(cat reference_errors)" >> $GITHUB_STEP_SUMMARY
            echo "Reference integrity errors found. Failing the workflow."
            exit 1
          else
            echo "Reference Integrity Check passed" >> $GITHUB_STEP_SUMMARY
          fi
